# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('descripcio', models.TextField(default='', max_length=500, verbose_name='Descripcio')),
                ('dia', models.DateTimeField(max_length=100, verbose_name='Inici')),
                ('diafinal', models.DateTimeField(max_length=100, verbose_name='Final')),
                ('creador', models.CharField(default='', max_length=250, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='activitat_persones_inscrites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistira', models.CharField(default='', max_length=2, verbose_name='assistira')),
                ('activitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitats.Activitat')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Localitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100, verbose_name='nom')),
                ('latitud', models.CharField(default='', max_length=100, verbose_name='latitud')),
                ('longitud', models.CharField(default='', max_length=100, verbose_name='longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('cognom', models.CharField(default='', max_length=50, verbose_name='Cognom')),
                ('correu', models.EmailField(default='', max_length=50, verbose_name='Correu electronic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nom del usuari')),
            ],
        ),
        migrations.AddField(
            model_name='activitat_persones_inscrites',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitats.Persona'),
        ),
        migrations.AddField(
            model_name='activitat',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitats.Categoria'),
        ),
        migrations.AddField(
            model_name='activitat',
            name='localitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitats.Localitat'),
        ),
        migrations.AddField(
            model_name='activitat',
            name='persones_inscrites',
            field=models.ManyToManyField(through='activitats.activitat_persones_inscrites', to='activitats.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='activitat_persones_inscrites',
            unique_together=set([('persona', 'activitat')]),
        ),
    ]
