# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activitats', '0002_comentari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentari',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='comentari',
            name='persona',
            field=models.CharField(default='', max_length=250, verbose_name='persona'),
        ),
    ]
