# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitats', '0004_comentari_id_activitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentari',
            name='id_activitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitats.Activitat', verbose_name='idactivitat'),
        ),
    ]
